package com.sopromadze.blogapi.model.role;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.NaturalId;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.persistence.*;
import org.hibernate.annotations.NaturalId;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a user role in the system.
 *
 * <p>Defines the different roles that users can have in the application.
 * Roles are stored in the database and associated with users through relationships.</p>
 *
 * @version 1.0
 * @since 12 de junio de 2025
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "roles")
public class Role {

	/**
	 * Unique identifier for the role
	 *
	 * <p>Automatically generated by the database using identity strategy</p>
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * Name of the role
	 *
	 * <p>Stored as an enumerated string value (RoleName enum).
	 * Marked as NaturalId for efficient lookups by role name.</p>
	 *
	 * @see RoleName
	 */
	@Enumerated(EnumType.STRING)
	@NaturalId
	@Column(name = "name")
	private RoleName name;

	/**
	 * Constructs a new Role with the specified name
	 *
	 * @param name The RoleName enum value to assign to this role
	 */
	public Role(RoleName name) {
		this.name = name;
	}
}