var searchData=
[
  ['a_20vulnerability_0',['Reporting a Vulnerability',['../md__s_e_c_u_r_i_t_y.html#autotoc_md27',1,'']]],
  ['album_20api_20albums_1',['&lt;a class=&quot;anchor&quot; id=&quot;albumcreate&quot;&gt;&lt;/a&gt;Create Album -&amp;gt; /api/albums',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['album_20api_20albums_20id_2',['&lt;a class=&quot;anchor&quot; id=&quot;albumupdate&quot;&gt;&lt;/a&gt;Update Album -&amp;gt; /api/albums/{id}',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['albums_3',['Albums',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['albums_4',['&lt;a class=&quot;anchor&quot; id=&quot;albumcreate&quot;&gt;&lt;/a&gt;Create Album -&amp;gt; /api/albums',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['albums_20id_5',['&lt;a class=&quot;anchor&quot; id=&quot;albumupdate&quot;&gt;&lt;/a&gt;Update Album -&amp;gt; /api/albums/{id}',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['api_6',['Spring Boot, MySQL, Spring Security, JWT, JPA, Rest API',['../md__r_e_a_d_m_e.html#autotoc_md0',1,'']]],
  ['api_20albums_7',['&lt;a class=&quot;anchor&quot; id=&quot;albumcreate&quot;&gt;&lt;/a&gt;Create Album -&amp;gt; /api/albums',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['api_20albums_20id_8',['&lt;a class=&quot;anchor&quot; id=&quot;albumupdate&quot;&gt;&lt;/a&gt;Update Album -&amp;gt; /api/albums/{id}',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['api_20auth_20signin_9',['&lt;a class=&quot;anchor&quot; id=&quot;signin&quot;&gt;&lt;/a&gt;Log In -&amp;gt; /api/auth/signin',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['api_20auth_20signup_10',['&lt;a class=&quot;anchor&quot; id=&quot;signup&quot;&gt;&lt;/a&gt;Sign Up -&amp;gt; /api/auth/signup',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['api_20photos_11',['&lt;a class=&quot;anchor&quot; id=&quot;photocreate&quot;&gt;&lt;/a&gt;Create Photo -&amp;gt; /api/photos',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['api_20photos_20id_12',['&lt;a class=&quot;anchor&quot; id=&quot;photoupdate&quot;&gt;&lt;/a&gt;Update Photo -&amp;gt; /api/photos{id}',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['api_20posts_13',['&lt;a class=&quot;anchor&quot; id=&quot;postcreate&quot;&gt;&lt;/a&gt;Create Post -&amp;gt; /api/posts',['../md__r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['api_20posts_20id_14',['&lt;a class=&quot;anchor&quot; id=&quot;postupdate&quot;&gt;&lt;/a&gt;Update Post -&amp;gt; /api/posts/{id}',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]],
  ['api_20posts_20postid_20comments_15',['&lt;a class=&quot;anchor&quot; id=&quot;commentcreate&quot;&gt;&lt;/a&gt;Create Comment -&amp;gt; /api/posts/{postId}/comments',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['api_20posts_20postid_20comments_20id_16',['&lt;a class=&quot;anchor&quot; id=&quot;commentupdate&quot;&gt;&lt;/a&gt;Update Comment -&amp;gt; /api/posts/{postId}/comments/{id}',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['api_20todos_17',['&lt;a class=&quot;anchor&quot; id=&quot;todocreate&quot;&gt;&lt;/a&gt;Create Todo -&amp;gt; /api/todos',['../md__r_e_a_d_m_e.html#autotoc_md24',1,'']]],
  ['api_20todos_20id_18',['&lt;a class=&quot;anchor&quot; id=&quot;todoupdate&quot;&gt;&lt;/a&gt;Update Todo -&amp;gt; /api/todos{id}',['../md__r_e_a_d_m_e.html#autotoc_md25',1,'']]],
  ['api_20users_19',['&lt;a class=&quot;anchor&quot; id=&quot;usercreate&quot;&gt;&lt;/a&gt;Create User -&amp;gt; /api/users',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['api_20users_20setorupdateinfo_20',['&lt;a class=&quot;anchor&quot; id=&quot;userinfoupdate&quot;&gt;&lt;/a&gt;Update User Profile -&amp;gt; /api/users/setOrUpdateInfo',['../md__r_e_a_d_m_e.html#autotoc_md15',1,'']]],
  ['api_20users_20username_21',['&lt;a class=&quot;anchor&quot; id=&quot;userupdate&quot;&gt;&lt;/a&gt;Update User -&amp;gt; /api/users/{username}',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['apis_22',['Explore Rest APIs',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['auth_23',['Auth',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['auth_20signin_24',['&lt;a class=&quot;anchor&quot; id=&quot;signin&quot;&gt;&lt;/a&gt;Log In -&amp;gt; /api/auth/signin',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['auth_20signup_25',['&lt;a class=&quot;anchor&quot; id=&quot;signup&quot;&gt;&lt;/a&gt;Sign Up -&amp;gt; /api/auth/signup',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]]
];
